services: 
  db: 
    image: postgres:15-alpine
    restart: always
    environment: 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports: 
      - "${DB_PORT}:5432"
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
  backend: 
    build: ./backend 
    env_file:
      - .env
    ports: 
      - "${PORT}:${PORT}"
    volumes: 
      - ./backend:/app/backend 
      - /app/backend/node_modules
    command: sh -c "npx wait-port db:5432 && npm run db:migrate && npm run db:seed && npm run start"
  frontend: 
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args: 
        - VUE_APP_ADRESS=${VUE_APP_ADRESS}
    env_file: 
      - .env
    ports: 
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend 
      - /app/frontend/node_modules


